export const IndiceStats = {
  // Capacités et Vœux [cite: 61]
  capa_fin: 0,
  voe_tot: 1,
  voe_tot_f: 2,
  nb_VOE_PP: 3,
  nb_VOE_PP_internat: 4,
  nb_VOE_PP_BG: 5,
  nb_VOE_PP_BG_brs: 6,
  nb_VOE_PP_BT: 7,
  nb_VOE_PP_BT_brs: 8,
  nb_VOE_PP_BP: 9,
  nb_VOE_PP_BP_brs: 10,
  nb_VOE_PP_at: 11,
  nb_VOE_PC: 12,
  nb_VOE_PC_BG: 13,
  nb_VOE_PC_BT: 14,
  nb_VOE_PC_BP: 15,
  nb_VOE_PC_at: 16,

  // Classements [cite: 62]
  nb_cla_PP: 17,
  nb_cla_PC: 18,
  nb_cla_pp_internat: 19,
  nb_cla_pp_pasinternat: 20,
  nb_cla_pp_BG: 21,
  nb_cla_pp_BG_brs: 22,
  nb_cla_pp_BT: 23,
  nb_cla_pp_BT_brs: 24,
  nb_cla_pp_BP: 25,
  nb_cla_pp_BP_brs: 26,
  nb_cla_pp_at: 27,

  // Admis et Propositions [cite: 63]
  Prop_tot: 28,
  Acc_tot: 29,
  Acc_tot_f: 30,
  Acc_PP: 31,
  Acc_PC: 32,
  acc_debutpp: 33,
  acc_datebac: 34,
  acc_finpp: 35,
  Acc_internat: 36,
  Acc_brs: 37,
  Acc_neobac: 38,
  Acc_BG: 39,
  Acc_BT: 40,
  Acc_BP: 41,
  Acc_at: 42,

  // Mentions et Origines [cite: 64]
  Acc_mention_nonrenseig_nee: 43,
  Acc_sansmention: 44,
  Acc_ab: 45,
  Acc_b: 46,
  Acc_tb: 47,
  Acc_tbf: 48,
  acc_BG_mention: 49,
  acc_BT_mention: 50,
  acc_BP_mention: 51,
  Acc_term: 52,
  Acc_term_f: 53,
  Acc_aca_orig: 54,
  Acc_aca_orig_idf: 55,

  // Pourcentages [cite: 65]
  pct_f: 56,
  pct_aca_orig: 57,
  pct_aca_orig_idf: 58,
  pct_etab_orig: 59,
  pct_bours: 60,
  pct_acc_debutpp: 61,
  pct_acc_datebac: 62,
  pct_acc_finpp: 63,
  pct_neobac: 64,
  pct_mention_nonrenseig_nee: 65,
  pct_sansmention: 66,
  pct_AB: 67,
  pct_B: 68,
  pct_TB: 69,
  pct_TBF: 70,
  pct_BG: 71,
  pct_BG_mention: 72,
  pct_BT: 73,
  pct_BT_mention: 74,
  pct_BP: 75,
  pct_BP_mention: 76,

  // Détails Propositions par Terminale [cite: 63]
  prop_tot_BG: 77,
  prop_tot_BG_brs: 78,
  prop_tot_BT: 79,
  prop_tot_BT_brs: 80,
  prop_tot_BP: 81,
  prop_tot_BP_brs: 82,
  prop_tot_at: 83,

  // Rangs et Indicateurs finaux [cite: 66, 67]
  ran_grp1: 84,
  ran_grp2: 85,
  ran_grp3: 86,
  Taux_acces_ens: 87,
  part_acces_gen: 88,
  part_acces_tec: 89,
  part_acces_pro: 90
} as const;
